inverter_reset:
  alias: Reset inverter to automatic mode
  mode: single
  description: Reset inverter to automatic mode
  fields:
    serial_number:
      required: true
      description: The serial number of the inverter
      example: RB20221443110059
      selector:
        text:
  fields_validation:
    serial_number: str
  service: redback_tech.inverter_reset
delete_all_schedules:
  alias: Delete all schedules
  description: Delete all schedules
  mode: single
  fields:
    serial_number:
      required: true
      description: The serial number of the inverter
      example: RB20221443110059
      selector:
        text:
  fields_validation:
    serial_number: str
  service: redback_tech.delete_all_schedules
create_schedule:
  alias: Create a schedule
  description: Create a schedule for the inverter
  mode: queued
  fields:
    serial_number:
      required: true
      description: The serial number of the inverter
      example: RB20221443110059
      selector:
        text:
    start_time:
      required: true
      description: The start time of the schedule
      example: 2022-03-22 07:00
      default: utcnow()
      selector:
        datetime:
    duration:
      required: true
      description: The duration of the schedule in minutes
      example: 25
      selector:
        number:
        min: 1
        max: 1440
        step: 1
    power:
      required: true
      description: The power level of the schedule
      example: 1000
      selector:
        number:
        min: 1
        max: 10000
        step: 1
    mode:
      required: true
      description: The mode of the schedule
      example: 'ChargeBattery'
      selector:
        select:
          options:
            - ChargeBattery
            - DischargeBattery
            - ImportPower
            - ExportPower
            - Conserve
  fields_validation:
    serial_number: str
    start_time: datetime
    duration: int
    power: int
  service: redback_tech.create_schedule
